# Rust plugin definitions
refs:
  - pip://nmk-base!plugin.yml

config:
    # Plugin version
    nmkRustPluginVersion:
        __resolver__: nmk_rust.NmkRustVersionResolver

    # Plugin versions dict
    nmkPluginsVersions:
        nmk-rust: ${nmkRustPluginVersion}

    # Plugin help links dict
    nmkPluginsDocs:
        nmk-rust: https://nmk-rust.readthedocs.io/
